name: build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows x64'
            os: windows-2019
            triplet: x64-windows
            vcpkg_dir: 'C:\vcpkg'
            vcpkg_export_dir: 'C:\vcpkg_export'
            suffix: 'windows-win32'
            generator: 'Visual Studio 16 2019'
            arch: '-A x64'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache vcpkg
        uses: actions/cache@v3.3.2
        with:
          path: '${{ matrix.vcpkg_dir }}/installed'
          key: vcpkg-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ matrix.triplet }}-

      - name: Install vcpkg packages
        shell: bash
        run: |
          vcpkg install --triplet ${{ matrix.triplet }}

      - name: Export vcpkg packages
        shell: bash
        run: |
          rd /q /s '${{matrix.vcpkg_export_dir}}'
          mkdir '${{matrix.vcpkg_export_dir}}/installed'
          xcopy c:\vcpkg_installed '${{matrix.vcpkg_export_dir}}/installed' /s /e /h
          xcopy '${{ matrix.vcpkg_dir }}/scripts' '${{matrix.vcpkg_export_dir}}' /s /e /h
          xcopy '${{ matrix.vcpkg_dir }}/.vcpkg-root' '${{matrix.vcpkg_export_dir}}' /s /e /h

          7z.exe a export-$date.7z .\vcpkg-export
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
            name: Release
            path: release